MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 2
  FASTER_RCNN: True
  MASK_ON: True
  NAME: east_weight_wh
NUM_GPUS: 4
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  # BASE_LR: 0.0001  #icdar13 
  BASE_LR: 0.005   #synth
  GAMMA: 0.1
  MAX_ITER: 200000
  STEPS: [0, 120000, 160000]
  # WEIGHT_DECAY: 0.0001
  # LR_POLICY: steps_with_decay
  # # BASE_LR: 0.0001  #icdar13 
  # BASE_LR: 0.0005   #synth
  # GAMMA: 0.1
  # MAX_ITER: 100000
  # STEPS: [0, 60000, 100000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
  USE_DEFORMABLE: False
  # RPN_ASPECT_RATIOS: (0.25, 0.5, 1, 2, 4)
  RPN_ASPECT_RATIOS: (0.5, 1, 2)
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
MRCNN:
  ROI_MASK_HEAD: text_mask_rcnn_heads.mask_rcnn_fcn_head_v1up4convs
  RESOLUTION: 28  # (output mask resolution) default 14
  RESOLUTION_H: 32
  RESOLUTION_W: 128
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14  # default 7
  ROI_XFORM_RESOLUTION_H: 16
  ROI_XFORM_RESOLUTION_W: 64
  ROI_XFORM_SAMPLING_RATIO: 2  # default 0
  DILATION: 1  # default 2
  CONV_INIT: MSRAFill  # default GaussianFill
  IS_E2E: True
  MASK_BATCH_SIZE_PER_IM: 16
  WEIGHT_LOSS_MASK: 1.0
  WEIGHT_WH: False  ## default is false 
TRAIN:
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  AUTO_RESUME: True
  SNAPSHOT_ITERS: 20000

  ##################### pre-train on synth ##########################
  WEIGHTS: https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl
  DATASETS: ('synth_train', )
  # DATASETS: ('icdar2013_train', )

  SCALES: (800,)
  MAX_SIZE: 1333
  IMS_PER_BATCH: 2
  ASPECT_GROUPING: True
  MIX_TRAIN: False

  ######################  Fine tune   #################################
  # MIX_TRAIN: True
  # WEIGHTS: ./train/synth_train/pretrain_model/model_iter159999.pkl



  # DATASETS: ('synth_train', 'icdar2013_train', 'icdar2015_train')
  # USE_CHARANNS: [True, False, False]
  ## the ratios of synth, icdar2013, icdar2015 is 2:1:1, defaultly

  # MIX_RATIOS: [0.5, 0.25, 0.25]
  # MIX_RATIOS: [0.25, 0.25, 0.5]

  # DATASETS: ('synth_train', 'icdar2013_train', 'icdar2015_train')
  # USE_CHARANNS: [True, False, False]
  # ## the ratios of synth, icdar2013, icdar2015 is 2:1:1, defaultly
  # # MIX_RATIOS: [0.5, 0.25, 0.25]
  # MIX_RATIOS: [0.25, 0.25, 0.5]

  # # # icdar13 && icdar15 are used for debug
  # # DATASETS: ('icdar2013_train', 'icdar2015_train')
  # # USE_CHARANNS: [True, False]
  # # MIX_RATIOS: [0.5, 0.5]
  # # # the ratios of synth, icdar2013, icdar2015 is 2:1:1, defaultly


  # SCALES: (600, 800, 1000, 1200)
  # MAX_SIZE: 1666
  # # SCALES: (800,)
  # # MAX_SIZE: 1333

  # IMS_PER_BATCH: 1
  # ASPECT_GROUPING: False




IMAGE:
  aug: False
  saturation_prob: 0.5
  saturation_lower: 0.5
  saturation_upper: 1.5
  hue_prob: 0.5
  hue_delta: 18
  lighting_noise_prob: 0.5
  contrast_prob: 0.5
  contrast_lower: 0.5
  contrast_upper: 1.5
  brightness_prob: 0.5
  brightness_delta: 32
  rotate_prob: 0.5
  rotate_delta: 15
TEST:
  # WEIGHTS: ./train/synth_train:icdar2013_train:icdar2015_train/generalized_rcnn/mix_finetune/model_final.pkl

  WEIGHTS: ./train/synth_train/generalized_rcnn/east/model_iter154999.pkl
  # WEIGHTS: ./train/synth_train:icdar2013_train:icdar2015_train/generalized_rcnn/mix_finetune_mix_aug/model_final.pkl
  DATASETS: ('icdar2013_test',)
  # DATASETS: ('synth0_train',)

  SCALES: (800,)
  MAX_SIZE: 2666
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
  VIS: True
OUTPUT_DIR: .

